# Uncomment this line to define a global platform for your project
source 'https://cdn.cocoapods.org/'
platform :ios, '9.3'

inhibit_all_warnings!
install! 'cocoapods',
  :warn_for_unused_master_specs_repo => false

target 'MusicPlayer' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  # Pods for MusicPlayer
  pod 'Masonry'

end
